### ISSUE TITLE
Error using multiprocQueueBase and multiprocTCPBase

### ISSUE THREAD

**Issue by harry-huang-maersk** [thespianpy/Thespian#61]
Hi there, 
My code works well with the simpleSystemBase but does not work in all three others (Queue, TCP, UDP). 
Here is the error message when running with multiprocQueueBase. 
![image](https://user-images.githubusercontent.com/70268752/107128821-14b03080-68c1-11eb-87f0-01358121cf58.png)
And the error when using multoprocTCPBase
![image](https://user-images.githubusercontent.com/70268752/107128845-49bc8300-68c1-11eb-85c5-ec11e8e7ce38.png)
I am running Python 3.7.5 and Thespian 3.10.3 
Here is the piece of code that I used. I am consuming messages from a Kafka topic. I will need to create about 5 million actors for the processing. 
![image](https://user-images.githubusercontent.com/70268752/107128896-a9b32980-68c1-11eb-9532-1e95c64a99f9.png)

And code for the two Actors. 
![image](https://user-images.githubusercontent.com/70268752/107128946-f26ae280-68c1-11eb-9d34-27f6cf5a1ef2.png)

Thanks for your help.

**Comment by kquick** [comment]
When using the multiproc bases, Thespian needs to be able to transport your messages between different system processes.  This is done by using the Python pickle protocol, but not all objects can be pickled.  You can find out more information about what can be pickled and how you can potentially pickle and unpickle additional objects at https://docs.python.org/3/library/pickle.html#what-can-be-pickled-and-unpickled.

Also you should note that a single system is not going to be able to accommodate 5 million processes.  I would recommend either sticking with the simpleSystemBase or else using a Thespian Convention of multiple systems.  Even the latter is probably not going to scale like you would hope, since the minimum memory footprint for a process running a Python instance is likely going to be your limiting factor.  Thespian is written on top of the Python VM, which is not designed for supporting large numbers of lightweight compute contexts like other Actor-specific VM's such as Erlang's Beam.

**Comment by harry-huang-maersk** [comment]
Thanks for the quick support. That clarifies what I need to know.

**Comment by kquick** [comment]
You're welcome, and good luck!
